name: deploy

on:
  create:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build app with Gradle
      run: chmod +x gradlew && ./gradlew shadowJar

    - uses: actions/checkout@v2
    - name: Copy app to server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        source: "build/libs/SimilarImagesBot-1.0.2-all.jar"
        target: "bots/similar-images-bot"
